### ISSUE TITLE
Parser changes

### ISSUE THREAD

**Issue by jaysnanavati** [LouvainVerificationLab/pynusmv#1]
Hi - I am looking to perform overwrites when parsing LTL formulas and wanted to find out what the best way to approach this would be. It would be great to have some pointers on this. Thanks

**Comment by sbusard** [comment]
Hello,

NuSMV parser is defined with Yacc/bison, and PyNuSMV provides no way to modify it or interfere in its process. The approach used by the tools already implemented with PyNuSMV (https://github.com/LouvainVerificationLab/pynusmv-tools) is to define a new parser whenever custom logic specifications have to be parsed. See for instance https://github.com/LouvainVerificationLab/pynusmv-tools/blob/master/pynusmv_tools/bmcLTL/parsing.py for an LTL parser.

Best regards.

**Comment by jaysnanavati** [comment]
Hi - Thanks for that! I will follow the same pattern :)
